In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style(style="darkgrid")# "whitegrid")
%matplotlib inline

In [2]:
df_group = pd.read_csv('Case Information_batch_3.csv')

In [3]:
df_group

,CaseCode,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
0,C46369460,23.0,20 to 24,MALE,2022-01-07,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,...,NCR,CITY OF PARAÑAQUE,PH137604000,B. F. HOMES,PH137604007,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
1,C69025406,7.0,5 to 9,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,...,RIZAL,ANGONO,PH045801000,SAN ISIDRO,PH045801009,RECOVERED,NO,2022-01-06,NO,"Health Status is ""Recovered"", but no Date Reco..."
2,C6572422,27.0,25 to 29,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,...,PAMPANGA,SANTA RITA,PH035420000,SAN VICENTE,PH035420009,RECOVERED,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
3,C16040871,17.0,15 to 19,FEMALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,RECOVERED,...,CEBU,CEBU CITY (CAPITAL),PH072217000,PARDO (POB.),PH072217053,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
4,C66405262,41.0,40 to 44,MALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,RECOVERED,...,NCR,CITY OF MAKATI,PH137602000,SINGKAMAS,PH137602027,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387519,C32778890,50.0,50 to 54,MALE,2022-01-19,2022-01-19,2022-01-22,NaN,NaN,NaN,...,NCR,CITY OF PARAÑAQUE,PH137604000,TAMBO,PH137604006,MILD,NO,NaN,NaN,NaN
387520,C28728958,36.0,35 to 39,MALE,2022-01-13,2022-01-14,2022-01-22,NaN,NaN,NaN,...,NCR,CITY OF MAKATI,PH137602000,PIO DEL PILAR,PH137602018,MILD,NO,NaN,NaN,NaN
387521,C95368764,37.0,35 to 39,MALE,2022-01-19,2022-01-20,2022-01-22,NaN,NaN,NaN,...,LEYTE,PALO,PH083739000,CAMPETIK,PH083739008,MILD,NO,NaN,NaN,NaN
387522,C59216411,10.0,10 to 14,FEMALE,2022-01-17,2022-01-20,2022-01-22,NaN,NaN,NaN,...,KALINGA,PASIL,PH143208000,BALENCIAGAO SUR,PH143208015,MILD,NO,NaN,NO,NaN
387523,C77787290,38.0,35 to 39,FEMALE,2022-01-19,2022-01-20,2022-01-22,NaN,NaN,NaN,...,LAGUNA,CITY OF CALAMBA,PH043405000,MAUNONG,PH043405031,MILD,NO,NaN,NO,NaN

In [4]:
df_group = df_group.set_index("CaseCode")
df_group.head()

,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,Admitted,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
CaseCode,,,,,,,,,,,,,,,,,,,,,
C46369460,23.0,20 to 24,MALE,2022-01-07,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,NaN,...,NCR,CITY OF PARAÑAQUE,PH137604000,B. F. HOMES,PH137604007,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
C69025406,7.0,5 to 9,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,NaN,...,RIZAL,ANGONO,PH045801000,SAN ISIDRO,PH045801009,RECOVERED,NO,2022-01-06,NO,"Health Status is ""Recovered"", but no Date Reco..."
C6572422,27.0,25 to 29,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,NaN,...,PAMPANGA,SANTA RITA,PH035420000,SAN VICENTE,PH035420009,RECOVERED,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
C16040871,17.0,15 to 19,FEMALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,RECOVERED,NaN,...,CEBU,CEBU CITY (CAPITAL),PH072217000,PARDO (POB.),PH072217053,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
C66405262,41.0,40 to 44,MALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,RECOVERED,NaN,...,NCR,CITY OF MAKATI,PH137602000,SINGKAMAS,PH137602027,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."

In [13]:
(df_group[df_group['ProvRes'] == 'ILOCOS SUR'])

,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,RemovalType,Admitted,...,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
CaseCode,,,,,,,,,,,,,,,,,,,,,
C1262675,26.0,25 to 29,MALE,2022-01-08,2022-01-10,2022-01-11,NaN,NaN,RECOVERED,NaN,...,ILOCOS SUR,CERVANTES,PH012908000,COMILLAS NORTH,PH012908002,RECOVERED,NO,2022-01-07,NaN,"Removal Type is ""Recovered"", but no Recovered ..."
C43874335,45.0,45 to 49,FEMALE,2022-01-07,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,NaN,...,ILOCOS SUR,CITY OF VIGAN (CAPITAL),PH012934000,BARANGAY V (POB.),PH012934007,RECOVERED,NO,2022-01-06,NO,"Removal Type is ""Recovered"", but no Recovered ..."
C40740561,37.0,35 to 39,FEMALE,2022-01-07,2022-01-08,2022-01-11,NaN,NaN,RECOVERED,NaN,...,ILOCOS SUR,CITY OF VIGAN (CAPITAL),PH012934000,BARANGAY V (POB.),PH012934007,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
C87078322,21.0,20 to 24,FEMALE,2022-01-09,2022-01-10,2022-01-11,NaN,NaN,RECOVERED,NaN,...,ILOCOS SUR,NARVACAN,PH012914000,DINALAOAN,PH012914013,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
C39174719,24.0,20 to 24,FEMALE,2022-01-03,2022-01-07,2022-01-11,NaN,NaN,RECOVERED,NaN,...,ILOCOS SUR,CITY OF CANDON,PH012906000,CALONGBUYAN,PH012906017,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C58249797,27.0,25 to 29,FEMALE,2022-01-19,2022-01-21,2022-01-22,NaN,NaN,NaN,NaN,...,ILOCOS SUR,SUYO,PH012932000,POBLACION (KIMPUSA),PH012932005,MILD,NO,2022-01-10,NO,NaN
C92173719,18.0,15 to 19,FEMALE,2022-01-18,2022-01-19,2022-01-22,NaN,NaN,NaN,NaN,...,ILOCOS SUR,CAOAYAN,PH012907000,DON LORENZO QUERUBIN (POB.),PH012907017,MILD,NO,2022-01-16,NO,NaN
C9516291,26.0,25 to 29,FEMALE,2022-01-18,2022-01-19,2022-01-22,NaN,NaN,NaN,NaN,...,ILOCOS SUR,MAGSINGAL,PH012912000,SAN BASILIO (POB.),PH012912032,MILD,NO,NaN,NO,NaN
C11348288,54.0,50 to 54,MALE,2022-01-19,2022-01-20,2022-01-22,NaN,NaN,NaN,NaN,...,ILOCOS SUR,SINAIT,PH012930000,DADALAQUITEN NORTE,PH012930014,MILD,NO,NaN,NaN,NaN
C18439871,1.0,0 to 4,FEMALE,2022-01-19,2022-01-20,2022-01-22,NaN,NaN,NaN,NaN,...,ILOCOS SUR,CABUGAO,PH012905000,BUNGRO,PH012905007,MILD,NO,2022-01-16,NO,NaN

In [5]:
y = targets = labels = output_var = df_group["RemovalType"]
x = predictors = input_var = df_group.loc[:,df_group.columns != "RemovalType"]

In [7]:
y.head()

CaseCode
C46369460    RECOVERED
C69025406    RECOVERED
C6572422     RECOVERED
C16040871    RECOVERED
C66405262    RECOVERED
Name: RemovalType, dtype: object

In [15]:
x.head()

,Age,AgeGroup,Sex,DateSpecimen,DateResultRelease,DateRepConf,DateDied,DateRecover,Admitted,RegionRes,ProvRes,CityMunRes,CityMuniPSGC,BarangayRes,BarangayPSGC,HealthStatus,Quarantined,DateOnset,Pregnanttab,ValidationStatus
CaseCode,,,,,,,,,,,,,,,,,,,,
C46369460,23.0,20 to 24,MALE,2022-01-07,2022-01-08,2022-01-11,NaN,NaN,NaN,NCR,NCR,CITY OF PARAÑAQUE,PH137604000,B. F. HOMES,PH137604007,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."
C69025406,7.0,5 to 9,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,NaN,Region IV-A: CALABARZON,RIZAL,ANGONO,PH045801000,SAN ISIDRO,PH045801009,RECOVERED,NO,2022-01-06,NO,"Health Status is ""Recovered"", but no Date Reco..."
C6572422,27.0,25 to 29,FEMALE,2022-01-06,2022-01-08,2022-01-11,NaN,NaN,NaN,Region III: Central Luzon,PAMPANGA,SANTA RITA,PH035420000,SAN VICENTE,PH035420009,RECOVERED,NO,NaN,NO,"Removal Type is ""Recovered"", but no Recovered ..."
C16040871,17.0,15 to 19,FEMALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,NaN,Region VII: Central Visayas,CEBU,CEBU CITY (CAPITAL),PH072217000,PARDO (POB.),PH072217053,RECOVERED,NO,NaN,NO,"Health Status is ""Recovered"", but no Date Reco..."
C66405262,41.0,40 to 44,MALE,2022-01-08,2022-01-09,2022-01-11,NaN,NaN,NaN,NCR,NCR,CITY OF MAKATI,PH137602000,SINGKAMAS,PH137602027,RECOVERED,NO,NaN,NaN,"Health Status is ""Recovered"", but no Date Reco..."